[project]
name = "waldur-prometheus-exporter-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prometheus-client==0.11.0",
    "waldur-api-client",
]

[tool.uv.sources]
waldur-api-client = { git = "https://github.com/waldur/py-client.git" }

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
  "I001",# isort
]
ignore = ["E501"]
fixable = ["ALL"]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true

